# Generated by Django 3.0.3 on 2020-05-29 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_agent_name', models.CharField(max_length=100)),
                ('contact_agent_email', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('part_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('item_location', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('IFX', 'IFX'), ('DC', 'DC Adapter'), ('ATX', 'ATX')], max_length=3)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Manufacturer')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('part_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('item_location', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('Micro-ATX', 'Micro-ATX'), ('Mini-ATX', 'Mini-ATX'), ('ATX', 'ATX'), ('Mini-ITX', 'Mini-ITX'), ('TPM', 'TPM Module')], max_length=30)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Manufacturer')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('part_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('item_location', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=4)),
                ('item_type', models.CharField(choices=[('LCD', 'LCD'), ('LED', 'LED')], max_length=6)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Manufacturer')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('part_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('item_location', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=4)),
                ('item_type', models.CharField(choices=[('DIMM', 'DIMMM'), ('SODIMM', 'SODIMM'), ('M.2', 'M.2')], max_length=6)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Manufacturer')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hard_Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('part_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('item_location', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=4)),
                ('item_type', models.CharField(choices=[('SSD', 'Solid State Drive'), ('M.2', 'M.2'), ('HDD', 'Mechanical Drive')], max_length=6)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Manufacturer')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('part_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('item_location', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=4)),
                ('item_type', models.CharField(choices=[('LP', 'Low Profile'), ('FH', 'Full Height'), ('HH', 'Half Height')], max_length=3)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Manufacturer')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('part_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('item_type', models.CharField(max_length=50)),
                ('item_location', models.CharField(max_length=50)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=3)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Manufacturer')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('part_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=30)),
                ('item_location', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('FT', 'Full Tower'), ('AIO', 'All In One'), ('Mini-PC', 'Mini-PC'), ('2u', '2U')], max_length=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Manufacturer')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
