# Generated by Django 3.0.3 on 2020-06-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['due_back']},
        ),
    ]
