# Generated by Django 3.0.3 on 2020-06-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplying',
        ),
    ]
